.TH WPSCRIPT 1

.SH NAME WPScript : a scripting language created for educational purpose.

.SH SYNOPSIS 
.B wpscript filepath : Execute the script in the file specified by filepath.

.B wpscript \-c commands : Execute the commands specified by commands.

.SH DESCRIPTION
.PP 
\fIWPScript\fP is an interpreter engine for the WPScript language.

.SH OPTIONS
When no option is provided, the first argument is used as a script file path to be read and executed.

.TP
.BI \-c 
The argument provided after \-c is direct WPScript commands to be executed.

.TP
.BI \-\-debug
Enable debug information output on the console (or on the redirected console output for script editor window).

.TP
.BI \-\-help, \-\-man
Displays this manual page

.TP
.BI \-\-version
Displays version information

.SH COPYRIGHT
 (c) 2011, FABRE Laurent.

.SH AUTHORS
Laurent FABRE, E-mail: laurent_psychedelic[at]hotmail.com
